# Generated by Django 5.0.8 on 2024-10-15 12:20

import base.files.storages
import user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=256, null=True, storage=base.files.storages.PrivateMediaFileSystemStorage(), upload_to=user.models.user.upload_to_user_avatar),
        ),
    ]
