# Generated by Django 5.0.8 on 2024-10-15 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbolic_path', models.CharField(help_text='Symbolic link from the Media Store to Filestore.', max_length=256, verbose_name='Symbolic Path')),
                ('store_path', models.CharField(help_text='Path in the Filestore.', max_length=256, verbose_name='Store Path')),
                ('checksum', models.CharField(help_text='SHA1 of the binary data of the file.', max_length=256, verbose_name='Checksum')),
                ('mimetype', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mimetype')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], help_text='Privacy means Media Store.', max_length=32, verbose_name='Privacy')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'File Reference',
                'verbose_name_plural': 'File References',
            },
        ),
        migrations.AddConstraint(
            model_name='filereference',
            constraint=models.UniqueConstraint(fields=('privacy', 'symbolic_path'), name='unique_symlink_privacy', violation_error_message='Only one symlink in the privacy store.'),
        ),
    ]
